// Photos de démonstration, embarquées : aucune requête vers une banque d'images.
// Chaque photo porte des traits sémantiques rédigés pour cette application :
// contexte familier, fonction, catégorie, début du mot (indice phonologique)
// et une question d'échange sans « bonne » réponse.
// Les indices phonologiques donnent le début du mot tel qu'il se prononce
// (une syllabe orale, ou le premier son pour un mot d'une seule syllabe).
const entries = [
  {
    id: "pomme",
    zones: ["cuisine", "jardin"],
    name: "Une pomme",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la trouve dans la corbeille de fruits, à la cuisine.",
    function:
      "Elle se croque, en dessert ou au goûter. On en fait aussi des tartes.",
    cue: "po…",
    talk: "Vous la préférez croquante ou en compote ?",
  },
  {
    id: "banane",
    zones: ["cuisine", "jardin"],
    name: "Des bananes",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On les achète en régime, au marché ou à l’épicerie.",
    function: "On les épluche avant de les manger, souvent au petit-déjeuner.",
    cue: "ba…",
    talk: "Vous en mangez au petit-déjeuner ?",
  },
  {
    id: "orange",
    zones: ["cuisine", "jardin"],
    name: "Une orange",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la trouve surtout en hiver, sur les étals du marché.",
    function: "On la pèle ou on la presse pour faire du jus.",
    cue: "o…",
    talk: "Plutôt en quartiers ou en jus ?",
  },
  {
    id: "carotte",
    zones: ["jardin", "cuisine"],
    name: "Des carottes",
    category: "Légumes",
    place: "Au potager",
    context: "Elles poussent dans la terre, au potager.",
    function: "On les râpe en salade ou on les cuit dans le pot-au-feu.",
    cue: "ca…",
    talk: "Râpées ou cuites, comment les aimez-vous ?",
  },
  {
    id: "brocoli",
    zones: ["jardin", "cuisine"],
    name: "Du brocoli",
    category: "Légumes",
    place: "Au potager",
    context: "On le trouve au rayon des légumes verts.",
    function: "On le cuit à la vapeur ou en gratin.",
    cue: "bro…",
    talk: "Vous en avez déjà cuisiné ?",
  },
  {
    id: "tomate",
    zones: ["jardin", "cuisine"],
    name: "Une tomate",
    category: "Légumes",
    place: "Au potager",
    context: "Elle mûrit au soleil, en été, au potager.",
    function: "On la coupe en salade ou on en fait de la sauce.",
    cue: "to…",
    talk: "Une salade de tomates, ça vous dit en été ?",
  },
  {
    id: "chat",
    name: "Un chat",
    category: "Animaux",
    place: "À la maison",
    context: "Il aime dormir au soleil, près de la fenêtre.",
    function: "C’est un animal de compagnie qui ronronne.",
    cue: "ch…",
    talk: "Avez-vous eu un chat ? Comment s’appelait-il ?",
  },
  {
    id: "chien",
    name: "Un chien",
    category: "Animaux",
    place: "À la maison",
    context: "On le promène en laisse, dans la rue ou au parc.",
    function: "C’est un compagnon fidèle qui aboie et garde la maison.",
    cue: "ch…",
    talk: "Plutôt les petits chiens ou les grands ?",
  },
  {
    id: "lapin",
    name: "Un lapin",
    category: "Animaux",
    place: "Au jardin",
    context: "On le voit dans les champs, ou dans un clapier à la ferme.",
    function: "Il a de grandes oreilles et aime les carottes.",
    cue: "la…",
    talk: "Avez-vous vu des lapins à la campagne ?",
  },
  {
    id: "lac",
    name: "Un lac",
    category: "Lieux",
    place: "Au bord du lac",
    context: "On s’y promène, entouré de montagnes et de forêts.",
    function: "On peut s’y baigner, pêcher ou faire du bateau.",
    cue: "la…",
    talk: "Plutôt une baignade ou une promenade au bord de l’eau ?",
    options: ["Une baignade", "Une promenade"],
  },
  {
    id: "montagne",
    name: "La montagne",
    category: "Lieux",
    place: "À la montagne",
    context: "Les sommets sont parfois couverts de neige.",
    function: "On y fait de la randonnée en été et du ski en hiver.",
    cue: "mon…",
    talk: "La montagne, vous l’aimez plutôt en été ou en hiver ?",
    options: ["En été", "En hiver"],
  },
  {
    id: "plage",
    name: "Une plage",
    category: "Lieux",
    place: "À la plage",
    context: "Le sable, la mer et les vacances d’été.",
    function: "On s’y baigne, on s’y repose au soleil.",
    cue: "pla…",
    talk: "Plutôt le sable chaud ou l’ombre d’un parasol ?",
    options: ["Le sable chaud", "L’ombre"],
  },
  {
    id: "maison",
    name: "Une maison",
    category: "Lieux",
    place: "Devant une maison",
    context: "Une maison avec un garage et une pelouse.",
    function: "C’est là que l’on habite, avec sa famille.",
    cue: "mai…",
    talk: "Dans une maison, quelle pièce préférez-vous ?",
    options: ["La cuisine", "Le jardin"],
  },
  {
    id: "jardin",
    name: "Des feuilles",
    category: "Nature",
    place: "Dans le jardin",
    context: "On les voit au jardin, après une averse.",
    function: "Elles poussent sur les plantes et les arbres.",
    cue: "feu…",
    talk: "Au jardin, plutôt les fleurs ou le potager ?",
    options: ["Les fleurs", "Le potager"],
  },
  {
    id: "chemise",
    zones: ["habits"],
    name: "Un tee-shirt",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On le range dans l’armoire, avec les vêtements d’été.",
    function: "On le porte quand il fait beau.",
    cue: "ti…",
    talk: "Plutôt un tee-shirt ou une chemise ?",
  },
  {
    id: "chaussures",
    zones: ["habits"],
    name: "Des chaussures",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On les laisse dans l’entrée, près de la porte.",
    function: "On les met aux pieds pour sortir et marcher.",
    cue: "chau…",
    talk: "Des chaussures confortables pour marcher, c’est important ?",
  },
  {
    id: "chapeau",
    zones: ["habits"],
    name: "Un chapeau de paille",
    category: "Vêtements",
    place: "À la plage",
    context: "On le prend pour aller à la plage ou au jardin.",
    function: "On le met sur la tête pour se protéger du soleil.",
    cue: "cha…",
    talk: "Portez-vous un chapeau quand il fait chaud ?",
  },
  {
    id: "pain",
    zones: ["cuisine"],
    name: "Du pain",
    category: "Objets",
    place: "Dans la corbeille à pain",
    context: "On l’achète chaque jour à la boulangerie.",
    function: "On en fait des tartines au petit-déjeuner.",
    cue: "p…",
    talk: "Plutôt la croûte ou la mie ?",
  },
  {
    id: "cafe",
    zones: ["cuisine"],
    name: "Une tasse de café",
    category: "Objets",
    place: "Sur la table du petit-déjeuner",
    context: "On la boit le matin, à la maison ou au café.",
    function: "On y boit le café, chaud.",
    cue: "ta…",
    talk: "Vous prenez votre café avec du sucre ?",
  },
  {
    id: "bouilloire",
    zones: ["cuisine"],
    name: "Une théière",
    category: "Objets",
    place: "Dans la cuisine",
    context: "On la pose sur la table, à côté des tasses.",
    function: "On y prépare le thé avec de l’eau chaude.",
    cue: "té…",
    talk: "Plutôt thé ou café ?",
  },
  {
    id: "brosse",
    zones: ["salle-de-bain"],
    name: "Une brosse à dents",
    category: "Objets",
    place: "Dans la salle de bain",
    context: "On la range dans un verre, dans la salle de bain.",
    function: "On s’en sert pour se brosser les dents, matin et soir.",
    cue: "bro…",
    talk: "Le matin, vous commencez par la toilette ou le petit-déjeuner ?",
  },
];
const SOUNDS = {
  chat: "assets/sons/chat.mp3",
  chien: "assets/sons/chien.mp3",
  lac: "assets/sons/eau.mp3",
};
export const PHOTOS = entries.map((e) => ({
  hint: "",
  options: null,
  zones: null,
  ...e,
  src: `assets/photos/${e.id}.jpg`,
  personal: false,
  sound: SOUNDS[e.id] || null,
}));
export const GAMES = [
  {
    id: "recognition",
    title: "Le mot juste",
    domain: "Dénomination · accès aux mots",
    description: "Nommer un objet familier, avec des aides pas à pas.",
    cover: "pomme",
  },
  {
    id: "sorting",
    title: "Ça sert à quoi ?",
    domain: "Associations · famille, usage, lieu",
    description: "Relier une photo à sa famille, son usage ou sa place.",
    cover: "bouilloire",
  },
  {
    id: "sequence",
    title: "Une consigne à la fois",
    domain: "Compréhension · gestes du quotidien",
    description: "Suivre de courtes consignes, une par une.",
    cover: "pain",
  },
  {
    id: "places",
    title: "Un lieu, un souvenir",
    domain: "Échange · réminiscence",
    description: "Regarder une photo et en parler, sans bonne réponse.",
    cover: "lac",
  },
  {
    id: "money",
    title: "À la boulangerie",
    domain: "Situations du quotidien",
    description: "Compter les pièces et rendre la monnaie.",
    cover: "pieces",
  },
  {
    id: "sounds",
    title: "À l’écoute",
    domain: "Sons familiers",
    description: "Écouter un son et retrouver sa photo.",
    cover: "chien",
  },
  {
    id: "memory",
    title: "Les photos jumelles",
    domain: "Observation · mémoire visuelle",
    description: "Retourner les cartes et réunir les paires.",
    cover: "chat",
  },
  {
    id: "odd",
    title: "Chacun sa famille",
    domain: "Catégories · attention",
    description: "Trouver la photo d’une famille donnée.",
    cover: "brocoli",
  },
  {
    id: "recall",
    title: "Dans mon panier",
    domain: "Mémoire · rappel",
    description: "Regarder quelques objets, puis les retrouver.",
    cover: "banane",
  },
  {
    id: "puzzle",
    title: "La photo à réunir",
    domain: "Assemblage visuel",
    description: "Recomposer une photo, pièce après pièce.",
    cover: "maison",
  },
];
// Scènes du quotidien pour « Une consigne à la fois » : une consigne courte,
// un seul verbe d'action et un seul objet à la fois.
export const SCENES = [
  {
    id: "petit-dejeuner",
    title: "Le petit-déjeuner",
    intro: "Nous préparons le petit-déjeuner.",
    steps: [
      {
        photo: "pain",
        say: "Touchez le pain.",
        after: "Le pain, pour les tartines.",
      },
      {
        photo: "bouilloire",
        say: "Touchez la théière.",
        after: "La théière, pour le thé chaud.",
      },
      { photo: "cafe", say: "Touchez la tasse.", after: "La tasse est prête." },
      {
        photo: "banane",
        say: "Touchez les bananes.",
        after: "Un fruit pour finir.",
      },
    ],
    extras: ["orange", "pomme"],
  },
  {
    id: "sortie",
    title: "Se préparer pour sortir",
    intro: "Il fait beau : nous nous préparons pour sortir.",
    steps: [
      {
        photo: "chemise",
        say: "Touchez le tee-shirt.",
        after: "Le tee-shirt, pour le beau temps.",
      },
      {
        photo: "chaussures",
        say: "Touchez les chaussures.",
        after: "Les chaussures, pour marcher.",
      },
      {
        photo: "chapeau",
        say: "Touchez le chapeau.",
        after: "Le chapeau, contre le soleil.",
      },
      {
        photo: "brosse",
        say: "Touchez la brosse à dents.",
        after: "La toilette est faite.",
      },
    ],
    extras: ["pain", "cafe"],
  },
  {
    id: "marche",
    title: "Au marché",
    intro: "Nous faisons les courses au marché.",
    steps: [
      {
        photo: "tomate",
        say: "Touchez la tomate.",
        after: "Une tomate pour la salade.",
      },
      {
        photo: "carotte",
        say: "Touchez les carottes.",
        after: "Des carottes pour la soupe.",
      },
      {
        photo: "pomme",
        say: "Touchez la pomme.",
        after: "Une pomme pour le dessert.",
      },
      {
        photo: "orange",
        say: "Touchez l’orange.",
        after: "Une orange pour le jus.",
      },
    ],
    extras: ["brocoli", "banane"],
  },
];
