// Photos de démonstration, embarquées : aucune requête vers une banque d'images.
// Chaque photo porte des traits sémantiques rédigés pour cette application :
// contexte familier, fonction, catégorie, début du mot (indice phonologique)
// et une question d'échange sans « bonne » réponse.
// Les indices phonologiques donnent le début du mot tel qu'il se prononce
// (une syllabe orale, ou le premier son pour un mot d'une seule syllabe).
const entries = [
  {
    id: "pomme",
    zones: ["cuisine", "jardin"],
    name: "Une pomme",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la trouve dans la corbeille de fruits, à la cuisine.",
    function:
      "Elle se croque, en dessert ou au goûter. On en fait aussi des tartes.",
    cue: "po…",
    talk: "Vous la préférez croquante ou en compote ?",
  },
  {
    id: "banane",
    zones: ["cuisine", "jardin"],
    name: "Des bananes",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On les achète en régime, au marché ou à l’épicerie.",
    function: "On les épluche avant de les manger, souvent au petit-déjeuner.",
    cue: "ba…",
    talk: "Vous en mangez au petit-déjeuner ?",
  },
  {
    id: "orange",
    zones: ["cuisine", "jardin"],
    name: "Une orange",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la trouve surtout en hiver, sur les étals du marché.",
    function: "On la pèle ou on la presse pour faire du jus.",
    cue: "o…",
    talk: "Plutôt en quartiers ou en jus ?",
  },
  {
    id: "carotte",
    zones: ["jardin", "cuisine"],
    name: "Des carottes",
    category: "Légumes",
    place: "Au potager",
    context: "Elles poussent dans la terre, au potager.",
    function: "On les râpe en salade ou on les cuit dans le pot-au-feu.",
    cue: "ca…",
    talk: "Râpées ou cuites, comment les aimez-vous ?",
  },
  {
    id: "brocoli",
    zones: ["jardin", "cuisine"],
    name: "Du brocoli",
    category: "Légumes",
    place: "Au potager",
    context: "On le trouve au rayon des légumes verts.",
    function: "On le cuit à la vapeur ou en gratin.",
    cue: "bro…",
    talk: "Vous en avez déjà cuisiné ?",
  },
  {
    id: "tomate",
    zones: ["jardin", "cuisine"],
    name: "Une tomate",
    category: "Légumes",
    place: "Au potager",
    context: "Elle mûrit au soleil, en été, au potager.",
    function: "On la coupe en salade ou on en fait de la sauce.",
    cue: "to…",
    talk: "Une salade de tomates, ça vous dit en été ?",
  },
  {
    id: "chat",
    name: "Un chat",
    category: "Animaux",
    place: "À la maison",
    context: "Il aime dormir au soleil, près de la fenêtre.",
    function: "C’est un animal de compagnie qui ronronne.",
    cue: "ch…",
    talk: "Avez-vous eu un chat ? Comment s’appelait-il ?",
  },
  {
    id: "chien",
    name: "Un chien",
    category: "Animaux",
    place: "À la maison",
    context: "On le promène en laisse, dans la rue ou au parc.",
    function: "C’est un compagnon fidèle qui aboie et garde la maison.",
    cue: "ch…",
    talk: "Plutôt les petits chiens ou les grands ?",
  },
  {
    id: "lapin",
    name: "Un lapin",
    category: "Animaux",
    place: "Au jardin",
    context: "On le voit dans les champs, ou dans un clapier à la ferme.",
    function: "Il a de grandes oreilles et aime les carottes.",
    cue: "la…",
    talk: "Avez-vous vu des lapins à la campagne ?",
  },
  {
    id: "lac",
    name: "Un lac",
    category: "Lieux",
    place: "Au bord du lac",
    context: "On s’y promène, entouré de montagnes et de forêts.",
    function: "On peut s’y baigner, pêcher ou faire du bateau.",
    cue: "la…",
    talk: "Plutôt une baignade ou une promenade au bord de l’eau ?",
    options: ["Une baignade", "Une promenade"],
  },
  {
    id: "montagne",
    name: "La montagne",
    category: "Lieux",
    place: "À la montagne",
    context: "Les sommets sont parfois couverts de neige.",
    function: "On y fait de la randonnée en été et du ski en hiver.",
    cue: "mon…",
    talk: "La montagne, vous l’aimez plutôt en été ou en hiver ?",
    options: ["En été", "En hiver"],
  },
  {
    id: "plage",
    name: "Une plage",
    category: "Lieux",
    place: "À la plage",
    context: "Le sable, la mer et les vacances d’été.",
    function: "On s’y baigne, on s’y repose au soleil.",
    cue: "pla…",
    talk: "Plutôt le sable chaud ou l’ombre d’un parasol ?",
    options: ["Le sable chaud", "L’ombre"],
  },
  {
    id: "maison",
    name: "Une maison",
    category: "Lieux",
    place: "Devant une maison",
    context: "Une maison avec un garage et une pelouse.",
    function: "C’est là que l’on habite, avec sa famille.",
    cue: "mai…",
    talk: "Dans une maison, quelle pièce préférez-vous ?",
    options: ["La cuisine", "Le jardin"],
  },
  {
    id: "jardin",
    name: "Des feuilles",
    category: "Nature",
    place: "Dans le jardin",
    context: "On les voit au jardin, après une averse.",
    function: "Elles poussent sur les plantes et les arbres.",
    cue: "feu…",
    talk: "Au jardin, plutôt les fleurs ou le potager ?",
    options: ["Les fleurs", "Le potager"],
  },
  {
    id: "chemise",
    zones: ["habits"],
    name: "Un tee-shirt",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On le range dans l’armoire, avec les vêtements d’été.",
    function: "On le porte quand il fait beau.",
    cue: "ti…",
    talk: "Plutôt un tee-shirt ou une chemise ?",
  },
  {
    id: "chaussures",
    zones: ["habits"],
    name: "Des chaussures",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On les laisse dans l’entrée, près de la porte.",
    function: "On les met aux pieds pour sortir et marcher.",
    cue: "chau…",
    talk: "Des chaussures confortables pour marcher, c’est important ?",
  },
  {
    id: "chapeau",
    zones: ["habits"],
    name: "Un chapeau de paille",
    category: "Vêtements",
    place: "À la plage",
    context: "On le prend pour aller à la plage ou au jardin.",
    function: "On le met sur la tête pour se protéger du soleil.",
    cue: "cha…",
    talk: "Portez-vous un chapeau quand il fait chaud ?",
  },
  {
    id: "pain",
    zones: ["cuisine"],
    name: "Du pain",
    category: "Objets",
    place: "Dans la corbeille à pain",
    context: "On l’achète chaque jour à la boulangerie.",
    function: "On en fait des tartines au petit-déjeuner.",
    cue: "p…",
    talk: "Plutôt la croûte ou la mie ?",
  },
  {
    id: "cafe",
    zones: ["cuisine"],
    name: "Une tasse de café",
    category: "Objets",
    place: "Sur la table du petit-déjeuner",
    context: "On la boit le matin, à la maison ou au café.",
    function: "On y boit le café, chaud.",
    cue: "ta…",
    talk: "Vous prenez votre café avec du sucre ?",
  },
  {
    id: "bouilloire",
    zones: ["cuisine"],
    name: "Une théière",
    category: "Objets",
    place: "Dans la cuisine",
    context: "On la pose sur la table, à côté des tasses.",
    function: "On y prépare le thé avec de l’eau chaude.",
    cue: "té…",
    talk: "Plutôt thé ou café ?",
  },
  {
    id: "brosse",
    zones: ["salle-de-bain"],
    name: "Une brosse à dents",
    category: "Objets",
    place: "Dans la salle de bain",
    context: "On la range dans un verre, dans la salle de bain.",
    function: "On s’en sert pour se brosser les dents, matin et soir.",
    cue: "bro…",
    talk: "Le matin, vous commencez par la toilette ou le petit-déjeuner ?",
  },
  // Photos ajoutées en version 4 (Fruits-360 et Clothing dataset).
  {
    id: "poire",
    zones: ["cuisine", "jardin"],
    name: "Une poire",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la cueille sur le poirier, à la fin de l’été.",
    function: "On la mange bien mûre, en dessert ou en compote.",
    cue: "p…",
    talk: "Plutôt une poire bien juteuse ou croquante ?",
  },
  {
    id: "prune",
    zones: ["cuisine", "jardin"],
    name: "Une prune",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la ramasse sous le prunier, en été.",
    function: "On en fait des tartes et de la confiture.",
    cue: "pr…",
    talk: "Une tarte aux prunes, ça vous rappelle quelque chose ?",
  },
  {
    id: "fraise",
    zones: ["cuisine", "jardin"],
    name: "Une fraise",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la cueille au jardin, au printemps.",
    function: "On la mange avec du sucre ou de la crème.",
    cue: "fr…",
    talk: "Les fraises, plutôt avec du sucre ou de la crème ?",
  },
  {
    id: "framboise",
    zones: ["cuisine", "jardin"],
    name: "Une framboise",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "Elle pousse sur un buisson, au fond du jardin.",
    function: "On la mange telle quelle ou en confiture.",
    cue: "fram…",
    talk: "Avez-vous déjà fait de la confiture de framboises ?",
  },
  {
    id: "mure",
    zones: ["cuisine", "jardin"],
    name: "Une mûre",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On la cueille le long des chemins, à la fin de l’été.",
    function: "On en fait de la confiture ou des tartes.",
    cue: "m…",
    talk: "Avez-vous cueilli des mûres le long d’un chemin ?",
  },
  {
    id: "melon",
    zones: ["cuisine", "jardin"],
    name: "Un melon",
    category: "Fruits",
    place: "Dans la corbeille de fruits",
    context: "On l’achète en été, au marché.",
    function: "On le coupe en tranches, bien frais.",
    cue: "me…",
    talk: "Le melon, plutôt en entrée ou en dessert ?",
  },
  {
    id: "poivron",
    zones: ["jardin", "cuisine"],
    name: "Un poivron",
    category: "Légumes",
    place: "Au potager",
    context: "Il mûrit au soleil, au potager.",
    function: "On le coupe en lamelles, cru ou cuit.",
    cue: "poi…",
    talk: "Rouge, vert ou jaune : quelle couleur préférez-vous ?",
  },
  {
    id: "oignon",
    zones: ["jardin", "cuisine"],
    name: "Un oignon",
    category: "Légumes",
    place: "Au potager",
    context: "On le garde dans un panier, à la cuisine.",
    function: "On l’épluche et on le fait revenir. Il fait pleurer !",
    cue: "o…",
    talk: "L’oignon vous fait-il pleurer quand vous l’épluchez ?",
  },
  {
    id: "chou",
    zones: ["jardin", "cuisine"],
    name: "Un chou",
    category: "Légumes",
    place: "Au potager",
    context: "Il pousse au potager, en hiver.",
    function: "On le cuit dans la potée ou en soupe.",
    cue: "ch…",
    talk: "Une bonne potée au chou, en hiver ?",
  },
  {
    id: "champignon",
    zones: ["jardin", "cuisine"],
    name: "Un champignon",
    category: "Légumes",
    place: "Au potager",
    context: "On le cueille en forêt, à l’automne, ou on l’achète au marché.",
    function: "On le fait revenir à la poêle, ou dans une omelette.",
    cue: "cham…",
    talk: "Avez-vous déjà cherché des champignons en forêt ?",
  },
  {
    id: "concombre",
    zones: ["jardin", "cuisine"],
    name: "Un concombre",
    category: "Légumes",
    place: "Au potager",
    context: "Il pousse au potager, en été.",
    function: "On le coupe en rondelles, en salade.",
    cue: "con…",
    talk: "Le concombre, plutôt à la crème ou en vinaigrette ?",
  },
  {
    id: "courgette",
    zones: ["jardin", "cuisine"],
    name: "Une courgette",
    category: "Légumes",
    place: "Au potager",
    context: "Elle pousse vite au potager, en été.",
    function: "On la fait en gratin ou en ratatouille.",
    cue: "cour…",
    talk: "Une ratatouille, ça vous dit ?",
  },
  {
    id: "ail",
    zones: ["jardin", "cuisine"],
    name: "L’ail",
    category: "Légumes",
    place: "Au potager",
    context: "On le garde en tresse, à la cuisine.",
    function: "On l’épluche et on l’écrase pour parfumer les plats.",
    cue: "a…",
    talk: "Mettez-vous de l’ail dans vos plats ?",
  },
  {
    id: "jean",
    near: ["pantalon"],
    zones: ["habits"],
    name: "Un jean",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On le range plié, dans l’armoire.",
    function: "On le porte tous les jours, il est solide.",
    cue: "dj…",
    talk: "Plutôt un jean ou un pantalon en tissu ?",
  },
  {
    id: "pantalon",
    zones: ["habits"],
    name: "Un pantalon",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On le range sur un cintre, dans l’armoire.",
    function: "On le porte pour sortir ou pour travailler.",
    cue: "pan…",
    talk: "Quelle couleur de pantalon aimez-vous porter ?",
  },
  {
    id: "claquettes",
    near: ["chaussures", "bottines"],
    zones: ["habits"],
    name: "Des claquettes",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On les met à la plage ou au bord de la piscine.",
    function: "On les enfile aux pieds, sans chaussettes.",
    cue: "cla…",
    talk: "Plutôt pieds nus ou en claquettes sur le sable ?",
  },
  {
    id: "bottines",
    near: ["chaussures", "claquettes"],
    zones: ["habits"],
    name: "Des bottines",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On les range dans l’entrée, pour l’hiver.",
    function: "On les met aux pieds quand il fait froid.",
    cue: "bo…",
    talk: "Des bottines à talons, vous en avez porté ?",
  },
  {
    id: "chemise-carreaux",
    zones: ["habits"],
    name: "Une chemise à carreaux",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On la suspend sur un cintre, dans l’armoire.",
    function: "On la boutonne pour sortir.",
    cue: "che…",
    talk: "Plutôt les carreaux ou les rayures ?",
  },
  {
    id: "robe",
    zones: ["habits"],
    name: "Une robe",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On la suspend dans l’armoire, pour les grandes occasions.",
    function: "On la met pour une fête ou un mariage.",
    cue: "r…",
    talk: "Vous souvenez-vous d’une robe portée pour une fête ?",
  },
  {
    id: "veste",
    zones: ["habits"],
    name: "Une veste",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On l’accroche au portemanteau, dans l’entrée.",
    function: "On la met pour sortir quand il fait frais.",
    cue: "v…",
    talk: "Une veste, ou un grand manteau en hiver ?",
  },
  {
    id: "bonnet",
    zones: ["habits"],
    name: "Un bonnet",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On le sort à l’automne, avec l’écharpe.",
    function: "On le met sur la tête quand il fait froid.",
    cue: "bo…",
    talk: "Un bonnet tricoté à la main, ça vous rappelle quelqu’un ?",
  },
  {
    id: "casquette",
    zones: ["habits"],
    name: "Une casquette",
    category: "Vêtements",
    place: "Dans l’entrée",
    context: "On la prend pour une promenade au soleil.",
    function: "On la met sur la tête pour protéger les yeux du soleil.",
    cue: "cas…",
    talk: "Qui portait une casquette dans votre famille ?",
  },
  {
    id: "jupe",
    zones: ["habits"],
    name: "Une jupe",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On la range dans l’armoire, avec les robes.",
    function: "On la porte avec un chemisier ou un pull.",
    cue: "j…",
    talk: "Plutôt une jupe longue ou une jupe courte ?",
  },
  {
    id: "pull",
    zones: ["habits"],
    name: "Un pull",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On le range plié, sur l’étagère de l’armoire.",
    function: "On le met quand il fait froid, pour avoir chaud.",
    cue: "p…",
    talk: "Avez-vous tricoté des pulls ?",
  },
  {
    id: "veste-costume",
    zones: ["habits"],
    name: "Une veste de costume",
    category: "Vêtements",
    place: "Dans l’armoire",
    context: "On la suspend sur un cintre, pour les grandes occasions.",
    function: "On la porte avec une cravate, pour un mariage.",
    cue: "v…",
    talk: "Pour quelle occasion met-on une veste de costume ?",
  },
];
const SOUNDS = {
  chat: "assets/sons/chat.mp3",
  chien: "assets/sons/chien.mp3",
  lac: "assets/sons/eau.mp3",
};
export const PHOTOS = entries.map((e) => ({
  hint: "",
  options: null,
  zones: null,
  ...e,
  src: `assets/photos/${e.id}.jpg`,
  personal: false,
  sound: SOUNDS[e.id] || null,
}));
export const GAMES = [
  {
    id: "family",
    title: "Ma famille",
    domain: "Famille · souvenirs",
    description: "Regarder les photos de la famille et en parler.",
    cover: "maison",
  },
  {
    id: "recognition",
    title: "Le mot juste",
    domain: "Dénomination · accès aux mots",
    description: "Nommer un objet familier, avec des aides pas à pas.",
    cover: "pomme",
  },
  {
    id: "sorting",
    title: "Ça sert à quoi ?",
    domain: "Associations · groupe, usage, lieu",
    description: "Relier une photo à son groupe, son usage ou sa place.",
    cover: "bouilloire",
  },
  {
    id: "sequence",
    title: "Une consigne à la fois",
    domain: "Compréhension · gestes du quotidien",
    description: "Suivre de courtes consignes, une par une.",
    cover: "pain",
  },
  {
    id: "places",
    title: "Une photo, un souvenir",
    domain: "Échange · réminiscence",
    description: "Regarder une photo et en parler, sans bonne réponse.",
    cover: "lac",
  },
  {
    id: "money",
    title: "À la boulangerie",
    domain: "Situations du quotidien",
    description: "Compter les pièces et rendre la monnaie.",
    cover: "pieces",
  },
  {
    id: "sounds",
    title: "À l’écoute",
    domain: "Sons familiers",
    description: "Écouter un son et retrouver sa photo.",
    cover: "chien",
  },
  {
    id: "memory",
    title: "Les photos jumelles",
    domain: "Observation · mémoire visuelle",
    description: "Retourner les cartes et réunir les paires.",
    cover: "chat",
  },
  {
    id: "odd",
    title: "Chacun son groupe",
    domain: "Catégories · attention",
    description: "Trouver le fruit, l’animal ou le vêtement demandé.",
    cover: "brocoli",
  },
  {
    id: "recall",
    title: "Dans mon panier",
    domain: "Mémoire · rappel",
    description: "Regarder quelques objets, puis les retrouver.",
    cover: "banane",
  },
  {
    id: "yesno",
    title: "Oui ou non ?",
    domain: "Compréhension · questions simples",
    description: "Répondre par oui ou par non à propos d’une photo.",
    cover: "poire",
  },
  {
    id: "pairs",
    title: "Ça va ensemble",
    domain: "Associations · situations",
    description: "Trouver ce qui va avec la photo.",
    cover: "claquettes",
  },
  {
    id: "expressions",
    title: "Les expressions de toujours",
    domain: "Langage · proverbes",
    description: "Finir un proverbe bien connu, ensemble.",
    cover: "chat",
  },
  {
    id: "prefer",
    title: "Ce qui me plaît",
    domain: "Choix · échange",
    description: "Choisir entre deux photos, sans bonne réponse.",
    cover: "plage",
  },
  {
    id: "puzzle",
    title: "La photo à réunir",
    domain: "Assemblage visuel",
    description: "Recomposer une photo, pièce après pièce.",
    cover: "maison",
  },
];
// Scènes du quotidien pour « Une consigne à la fois » : une consigne courte,
// un seul verbe d'action et un seul objet à la fois.
export const SCENES = [
  {
    id: "petit-dejeuner",
    title: "Le petit-déjeuner",
    intro: "Nous préparons le petit-déjeuner.",
    steps: [
      {
        photo: "pain",
        say: "Touchez le pain.",
        after: "Le pain, pour les tartines.",
      },
      {
        photo: "bouilloire",
        say: "Touchez la théière.",
        after: "La théière, pour le thé chaud.",
      },
      { photo: "cafe", say: "Touchez la tasse.", after: "La tasse est prête." },
      {
        photo: "banane",
        say: "Touchez les bananes.",
        after: "Un fruit pour finir.",
      },
    ],
    extras: ["orange", "pomme"],
  },
  {
    id: "sortie",
    title: "Se préparer pour sortir",
    intro: "Il fait beau : nous nous préparons pour sortir.",
    steps: [
      {
        photo: "chemise",
        say: "Touchez le tee-shirt.",
        after: "Le tee-shirt, pour le beau temps.",
      },
      {
        photo: "chaussures",
        say: "Touchez les chaussures.",
        after: "Les chaussures, pour marcher.",
      },
      {
        photo: "chapeau",
        say: "Touchez le chapeau.",
        after: "Le chapeau, contre le soleil.",
      },
      {
        photo: "brosse",
        say: "Touchez la brosse à dents.",
        after: "La toilette est faite.",
      },
    ],
    extras: ["pain", "cafe"],
  },
  {
    id: "marche",
    title: "Au marché",
    intro: "Nous faisons les courses au marché.",
    steps: [
      {
        photo: "tomate",
        say: "Touchez la tomate.",
        after: "Une tomate pour la salade.",
      },
      {
        photo: "carotte",
        say: "Touchez les carottes.",
        after: "Des carottes pour la soupe.",
      },
      {
        photo: "pomme",
        say: "Touchez la pomme.",
        after: "Une pomme pour le dessert.",
      },
      {
        photo: "orange",
        say: "Touchez l’orange.",
        after: "Une orange pour le jus.",
      },
    ],
    extras: ["brocoli", "banane"],
  },
  {
    id: "hiver",
    title: "S’habiller pour l’hiver",
    intro: "Il fait froid dehors : nous nous habillons chaudement.",
    steps: [
      {
        photo: "pull",
        say: "Touchez le pull.",
        after: "Le pull, pour avoir chaud.",
      },
      {
        photo: "bottines",
        say: "Touchez les bottines.",
        after: "Les bottines, contre le froid.",
      },
      {
        photo: "veste",
        say: "Touchez la veste.",
        after: "La veste, pour sortir.",
      },
      {
        photo: "bonnet",
        say: "Touchez le bonnet.",
        after: "Le bonnet, pour les oreilles.",
      },
    ],
    extras: ["claquettes", "chapeau", "chemise"],
  },
  {
    id: "soupe",
    title: "La soupe de légumes",
    intro: "Nous préparons une bonne soupe de légumes.",
    steps: [
      {
        photo: "oignon",
        say: "Touchez l’oignon.",
        after: "L’oignon, pour le goût.",
      },
      {
        photo: "carotte",
        say: "Touchez les carottes.",
        after: "Les carottes, pour la couleur.",
      },
      {
        photo: "courgette",
        say: "Touchez la courgette.",
        after: "La courgette, coupée en dés.",
      },
      {
        photo: "chou",
        say: "Touchez le chou.",
        after: "Le chou, et la soupe est prête.",
      },
    ],
    extras: ["fraise", "melon", "pain"],
  },
  {
    id: "dessert",
    title: "Une salade de fruits",
    intro: "Nous préparons une salade de fruits pour le dessert.",
    steps: [
      {
        photo: "fraise",
        say: "Touchez la fraise.",
        after: "La fraise, bien rouge.",
      },
      {
        photo: "poire",
        say: "Touchez la poire.",
        after: "La poire, coupée en morceaux.",
      },
      {
        photo: "banane",
        say: "Touchez les bananes.",
        after: "La banane, en rondelles.",
      },
      {
        photo: "melon",
        say: "Touchez le melon.",
        after: "Le melon, bien frais.",
      },
    ],
    extras: ["oignon", "ail", "chou"],
  },
];
// « Ça va ensemble » : associations d'usage ou de situation, créées pour
// cette application. Les distracteurs sont choisis à la main pour n'avoir
// aucun lien plausible avec la photo de départ.
export const PAIRS = [
  {
    from: "lapin",
    to: "carotte",
    why: "Le lapin aime grignoter les carottes.",
    not: ["chaussures", "bouilloire", "robe"],
  },
  {
    from: "chapeau",
    to: "plage",
    why: "Le chapeau de paille protège du soleil à la plage.",
    not: ["oignon", "chou", "brosse"],
  },
  {
    from: "bonnet",
    to: "montagne",
    why: "À la montagne, en hiver, on met un bonnet.",
    not: ["plage", "fraise", "claquettes"],
  },
  {
    from: "claquettes",
    to: "plage",
    why: "On marche en claquettes sur le sable.",
    not: ["montagne", "pull", "chou"],
  },
  {
    from: "pain",
    to: "cafe",
    why: "Du pain et un café pour le petit-déjeuner.",
    not: ["chaussures", "lapin", "bonnet"],
  },
  {
    from: "pull",
    to: "bonnet",
    why: "Le pull et le bonnet tiennent chaud en hiver.",
    not: ["claquettes", "fraise", "plage"],
  },
  {
    from: "concombre",
    to: "tomate",
    why: "Le concombre et la tomate, pour une salade d’été.",
    not: ["chaussures", "brosse", "bonnet"],
  },
  {
    from: "bouilloire",
    to: "cafe",
    why: "La théière et la tasse, pour une boisson chaude.",
    not: ["jean", "chou", "chien"],
  },
  {
    from: "fraise",
    to: "framboise",
    why: "La fraise et la framboise : deux fruits rouges de l’été.",
    not: ["oignon", "chaussures", "veste"],
  },
  {
    from: "robe",
    to: "bottines",
    why: "Une robe et des bottines, pour une sortie.",
    not: ["chou", "lapin", "bouilloire"],
  },
  {
    from: "veste-costume",
    to: "chemise-carreaux",
    why: "On porte une chemise sous la veste.",
    not: ["melon", "chat", "ail"],
  },
  {
    from: "chien",
    to: "maison",
    why: "Le chien garde la maison.",
    not: ["fraise", "brosse", "jupe"],
  },
];
// « Les expressions de toujours » : proverbes et expressions populaires du
// domaine public, à compléter. Le langage automatique est souvent mieux
// préservé : c'est un plaisir à partager, pas un test.
export const PROVERBS = [
  {
    start: "Petit à petit, l’oiseau fait son…",
    end: "nid",
    others: ["lit", "chemin", "pain"],
  },
  {
    start: "Après la pluie, le beau…",
    end: "temps",
    others: ["jardin", "chapeau", "soir"],
  },
  {
    start: "Qui vole un œuf vole un…",
    end: "bœuf",
    others: ["chat", "pain", "vélo"],
  },
  {
    start: "L’habit ne fait pas le…",
    end: "moine",
    others: ["jardin", "pain", "chapeau"],
  },
  {
    start: "Pierre qui roule n’amasse pas…",
    end: "mousse",
    others: ["sable", "argent", "pierres"],
  },
  {
    start: "Quand le chat n’est pas là, les souris…",
    end: "dansent",
    others: ["dorment", "mangent", "partent"],
    photo: "chat",
  },
  {
    start: "La nuit, tous les chats sont…",
    end: "gris",
    others: ["noirs", "blancs", "beaux"],
    photo: "chat",
  },
  {
    start: "Mieux vaut tard que…",
    end: "jamais",
    others: ["demain", "toujours", "souvent"],
  },
  { start: "Tel père, tel…", end: "fils", others: ["frère", "voisin", "ami"] },
  {
    start: "Chose promise, chose…",
    end: "due",
    others: ["faite", "vue", "dite"],
  },
  {
    start: "En avril, ne te découvre pas d’un…",
    end: "fil",
    others: ["pied", "pull", "mois"],
    photo: "pull",
  },
  {
    start: "Rien ne sert de courir, il faut partir à…",
    end: "point",
    others: ["pied", "midi", "temps"],
  },
  {
    start: "Une hirondelle ne fait pas le…",
    end: "printemps",
    others: ["nid", "jardin", "voyage"],
  },
  {
    start: "C’est en forgeant qu’on devient…",
    end: "forgeron",
    others: ["boulanger", "jardinier", "fort"],
  },
  {
    start: "Les petits ruisseaux font les grandes…",
    end: "rivières",
    others: ["montagnes", "maisons", "routes"],
    photo: "lac",
  },
  {
    start: "Noël au balcon, Pâques au…",
    end: "tison",
    others: ["jardin", "salon", "marché"],
  },
  {
    start: "Il faut battre le fer pendant qu’il est…",
    end: "chaud",
    others: ["froid", "neuf", "lourd"],
  },
  {
    start: "Qui sème le vent récolte la…",
    end: "tempête",
    others: ["pluie", "moisson", "neige"],
  },
  {
    start: "Qui se ressemble s’…",
    end: "assemble",
    others: ["amuse", "attend", "endort"],
  },
  {
    start: "Un tiens vaut mieux que deux tu l’…",
    end: "auras",
    others: ["aimes", "as", "veux"],
  },
];
// « Oui ou non ? » : des questions simples sur une photo. Chaque question
// indique les familles pour lesquelles la réponse est « oui », et celles pour
// lesquelles c'est clairement « non » (les cas ambigus sont exclus).
export const YESNO = [
  {
    ask: "Est-ce un fruit ?",
    yes: ["Fruits"],
    no: ["Vêtements", "Animaux", "Objets", "Lieux"],
  },
  {
    ask: "Est-ce un légume ?",
    yes: ["Légumes"],
    no: ["Vêtements", "Animaux", "Objets", "Lieux"],
  },
  {
    ask: "Est-ce un animal ?",
    yes: ["Animaux"],
    no: ["Fruits", "Légumes", "Vêtements", "Objets"],
  },
  {
    ask: "Est-ce que cela se porte sur soi ?",
    yes: ["Vêtements"],
    no: ["Fruits", "Légumes", "Animaux", "Lieux"],
  },
  {
    ask: "Est-ce que cela se mange ?",
    yes: ["Fruits", "Légumes"],
    no: ["Vêtements", "Lieux"],
  },
  {
    ask: "Est-ce un lieu ?",
    yes: ["Lieux"],
    no: ["Fruits", "Légumes", "Vêtements", "Objets"],
  },
];
